#! /bin/sh
# /etc/init.d/dyn-dns 

### BEGIN INIT INFO
# Provides:          dyn-ip
# Required-Start:    $remote_fs $syslog
# Default-Start:     2 3 4 5
# Short-Description: Starts dyn-ip as a cron at boot
# Description:       Starts dyn-ip as a cron at boot. More info under https://github.com/nbaudet/dyn-ip
### END INIT INFO

# Author: Nicolas Baudet

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting dyn-ip"
    sudo /usr/local/bin/node /home/volumio/dyn-ip/app.js
    ;;
  *)
    echo "Usage: /etc/init.d/dyn-ip {start}"
    exit 1
    ;;
esac

exit 0
